language: c

os: linux
dist: trusty


compiler: arm-none-eabi-gcc


before_install:
  -  sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  -  sudo apt-get update -q
  -  sudo apt-get install gcc-arm-embedded -y


script:
  -  cd board/TencentOS_tiny_EVB_MX/GCC/hello_world
  -  make


